initStore([
  {
    id: 0,
    title: 'Elden Ring (PC/PS5/Xbox)',
    description: 'Venture through a dark open world filled with danger, lore, and epic battles.',
    price: 69.95,
    discountPrice: 54.95,
    image: 'images/service-1.jpg',
  },
  {
    id: 1,
    title: 'Call of Duty: Modern Warfare II (PC/PS5/Xbox)',
    description: 'Fast-paced shooter with intense missions and competitive multiplayer.',
    price: 79.95,
    discountPrice: 59.95,
    image: 'images/service-2.jpg',
  },
  {
    id: 2,
    title: 'The Legend of Zelda: Tears of the Kingdom (Switch)',
    description: 'Explore floating islands and solve mysteries in a stunning adventure.',
    price: 69.95,
    discountPrice: 62.95,
    image: 'images/service-3.jpg',
  },
  {
    id: 3,
    title: 'EA Sports FC 24 (PC/PS5/Xbox)',
    description: 'Realistic football action with updated teams and smooth gameplay.',
    price: 59.95,
    discountPrice: 49.95,
    image: 'images/service-4.jpg',
  },
  {
    id: 4,
    title: 'Resident Evil Village (PC/PS5/Xbox)',
    description: 'Survive horrors in a creepy village filled with deadly secrets.',
    price: 39.95,
    discountPrice: 29.95,
    image: 'images/service-5.jpg',
  },
  {
    id: 5,
    title: 'Super Smash Bros. Ultimate (Switch)',
    description: 'Battle with classic characters in chaotic multiplayer brawls.',
    price: 59.95,
    discountPrice: 49.95,
    image: 'images/service-6.jpg',
  },
]);